-- 既存の users.username を小文字に正規化する。
-- username はメールアドレス・任意のユーザーIDのどちらでも、書式で分岐させず常に
-- 小文字で保存・照合する (docs/design.md 10章)。列定義と UNIQUE 制約は変更せず、
-- アプリ側の正規化 (auth::normalize_username) と、この既存行の一括変換で担保する。
--
-- 小文字化した結果 username が衝突する場合は UNIQUE 制約違反となり、このマイグレーション
-- は失敗してサーバー起動が中断する。家族向け・少人数利用のアプリであり、衝突は事前検出
-- するより起動時に気づいて手動で解消する方が単純なため、意図的に事前チェックを入れない。
--
-- SQLite の lower() は ASCII のみを小文字化する。アプリ側も to_ascii_lowercase() を
-- 使うことで、既存行と新規行の正規化結果が食い違わないようにしている。
UPDATE users SET username = lower(username);
